fn main() {
    println!("cargo:rerun-if-changed=../../proto/ipc.proto");
    prost_build::compile_protos(&["../../proto/ipc.proto"], &["../../proto/"])
        .expect("Failed to compile proto files");

    generate_paths();
    compile_mo_files();
}

fn compile_mo_files() {
    if std::env::var("CARGO_FEATURE_L10N_DEBUG").is_err() {
        return;
    }

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let po_dir = std::path::Path::new(&manifest_dir)
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("po");
    if !po_dir.exists() {
        return;
    }

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let mo_root = std::path::Path::new(&out_dir).join("mo");

    for entry in std::fs::read_dir(&po_dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("po") {
            continue;
        }
        let lang = path.file_stem().unwrap().to_str().unwrap();
        let mo_subdir = mo_root.join(lang).join("LC_MESSAGES");
        std::fs::create_dir_all(&mo_subdir).unwrap();

        let mo_path = mo_subdir.join("systema.mo");
        let status = std::process::Command::new("msgfmt")
            .arg(&path)
            .arg("-o")
            .arg(&mo_path)
            .status()
            .expect("msgfmt not found — install gettext tools");
        if !status.success() {
            panic!("msgfmt failed for {:?}", path);
        }
        println!("cargo:rerun-if-changed={}", path.display());
    }
}

fn generate_paths() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest_path = std::path::Path::new(&out_dir).join("paths.rs");

    let content = r#"// Generated by build.rs — do not edit.
// Compile-time default paths. Override at runtime via environment variables.

pub const SYSTEMD_LIB_UNIT_DIR: &str = "/usr/lib/systemd/system";
pub const SYSTEMD_FIRST_BOOT_FILE: &str = "/run/systemd/first-boot";
pub const SYSTEMD_MACHINE_ID_FILE: &str = "/etc/machine-id";

pub const IPC_SOCKET_PATH: &str = "/run/system-alphabet/allocator.sock";
pub const SYSTEMA_FDPASS_SOCK: &str = "/run/system-alphabet/fdpass.sock";

pub const NOTIFY_DIR: &str = "/run/system-alphabet/notify";

pub const SYSTEMA_SHELL_PATH: &str = "/bin/sh";
pub const SYSTEMA_SOCKET_HANDLER_PATH: &str = "/usr/lib/system-alphabet/socket-handler";

pub const LOCALE_DIR: &str = "/usr/share/locale";

pub const UNIT_SEARCH_PATHS: &[&str] = &[
    "/etc/system-alphabet",
    "/run/system-alphabet",
    "/usr/local/lib/system-alphabet",
    "/usr/lib/system-alphabet",
    "/etc/systemd/system",
    "/usr/lib/systemd/system",
    "/lib/systemd/system",
];

pub const GENERATOR_SEARCH_PATHS: &[&str] = &[
    "/run/systemd/generator",
    "/run/systemd/generator.late",
    "/etc/systemd/system-generators",
    "/usr/local/lib/systemd/system-generators",
    "/usr/lib/systemd/system-generators",
    "/lib/systemd/system-generators",
];

pub const SYSTEMA_BIN_SEARCH_PATHS: &[&str] = &[
    "/",
    "/bin",
    "/sbin",
    "/lib/systema",
    "/libexec/systema",
    "/usr/bin",
    "/usr/sbin",
    "/usr/lib/systema",
    "/usr/libexec/systema",
    "/usr/local/bin",
    "/usr/local/sbin",
    "/usr/local/lib/systema",
    "/usr/local/libexec/systema",
    "/opt/systema",
];
"#;

    std::fs::write(&dest_path, content).unwrap();
}
