fn main() {
    prost_build::compile_protos(&["../../proto/ipc.proto"], &["../../proto/"])
        .expect("Failed to compile proto files");

    generate_paths();
}

fn get_path_list(env_var: &str, default: &str) -> Vec<String> {
    let raw = std::env::var(env_var).unwrap_or_else(|_| default.to_string());
    raw.split(':').map(|s| s.trim().to_string()).collect()
}

fn generate_paths() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest_path = std::path::Path::new(&out_dir).join("paths.rs");

    let unit_path = get_path_list(
        "SYSTEMA_UNIT_PATH",
        "/etc/system-alphabet:/run/system-alphabet:\
         /usr/local/lib/system-alphabet:/usr/lib/system-alphabet:\
         /etc/systemd/system:/usr/lib/systemd/system:/lib/systemd/system",
    );
    let generator_path = get_path_list(
        "SYSTEMA_GENERATOR_PATH",
        "/run/systemd/generator:/run/systemd/generator.late:\
         /etc/systemd/system-generators:/usr/local/lib/systemd/system-generators:\
         /usr/lib/systemd/system-generators:/lib/systemd/system-generators",
    );

    let lib_unit_dir = std::env::var("SYSTEMD_LIB_UNIT_DIR")
        .unwrap_or_else(|_| "/usr/lib/systemd/system".to_string());
    let first_boot = std::env::var("SYSTEMD_FIRST_BOOT_FILE")
        .unwrap_or_else(|_| "/run/systemd/first-boot".to_string());
    let machine_id = std::env::var("SYSTEMD_MACHINE_ID_FILE")
        .unwrap_or_else(|_| "/etc/machine-id".to_string());
    let ipc_socket = std::env::var("SYSTEMA_IPC_SOCKET")
        .unwrap_or_else(|_| "/run/system-alphabet/allocator.sock".to_string());
    let fdpass_sock = std::env::var("SYSTEMA_FDPASS_SOCK")
        .unwrap_or_else(|_| "/run/system-alphabet/fdpass.sock".to_string());
    let shell_path = std::env::var("SYSTEMA_SHELL_PATH")
        .unwrap_or_else(|_| "/bin/sh".to_string());
    let socket_handler_path = std::env::var("SYSTEMA_SOCKET_HANDLER_PATH")
        .unwrap_or_else(|_| "/usr/lib/system-alphabet/socket-handler".to_string());

    let unit_paths_entries: String = unit_path
        .iter()
        .map(|p| format!("    \"{p}\","))
        .collect::<Vec<_>>()
        .join("\n");
    let gen_paths_entries: String = generator_path
        .iter()
        .map(|p| format!("    \"{p}\","))
        .collect::<Vec<_>>()
        .join("\n");

    let content = format!(
        r#"// Generated by build.rs — do not edit.
// Paths can be overridden at compile time via environment variables.

pub const SYSTEMD_LIB_UNIT_DIR: &str = "{lib_unit_dir}";
pub const SYSTEMD_FIRST_BOOT_FILE: &str = "{first_boot}";
pub const SYSTEMD_MACHINE_ID_FILE: &str = "{machine_id}";

pub const IPC_SOCKET_PATH: &str = "{ipc_socket}";
pub const SYSTEMA_FDPASS_SOCK: &str = "{fdpass_sock}";

pub const SYSTEMA_SHELL_PATH: &str = "{shell_path}";
pub const SYSTEMA_SOCKET_HANDLER_PATH: &str = "{socket_handler_path}";

pub const UNIT_SEARCH_PATHS: &[&str] = &[
{unit_paths_entries}
];

pub const GENERATOR_SEARCH_PATHS: &[&str] = &[
{gen_paths_entries}
];
"#,
        lib_unit_dir = lib_unit_dir,
        first_boot = first_boot,
        machine_id = machine_id,
        ipc_socket = ipc_socket,
        fdpass_sock = fdpass_sock,
        shell_path = shell_path,
        socket_handler_path = socket_handler_path,
        unit_paths_entries = unit_paths_entries,
        gen_paths_entries = gen_paths_entries,
    );

    std::fs::write(&dest_path, content).unwrap();

    println!("cargo:rerun-if-env-changed=SYSTEMD_LIB_UNIT_DIR");
    println!("cargo:rerun-if-env-changed=SYSTEMA_UNIT_PATH");
    println!("cargo:rerun-if-env-changed=SYSTEMA_GENERATOR_PATH");
    println!("cargo:rerun-if-env-changed=SYSTEMD_FIRST_BOOT_FILE");
    println!("cargo:rerun-if-env-changed=SYSTEMD_MACHINE_ID_FILE");
    println!("cargo:rerun-if-env-changed=SYSTEMA_IPC_SOCKET");
    println!("cargo:rerun-if-env-changed=SYSTEMA_FDPASS_SOCK");
    println!("cargo:rerun-if-env-changed=SYSTEMA_SHELL_PATH");
    println!("cargo:rerun-if-env-changed=SYSTEMA_SOCKET_HANDLER_PATH");
}
