fn main() {
    prost_build::compile_protos(&["../../proto/ipc.proto"], &["../../proto/"])
        .expect("Failed to compile proto files");

    generate_paths();
}

fn generate_paths() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest_path = std::path::Path::new(&out_dir).join("paths.rs");

    let content = r#"// Generated by build.rs — do not edit.
// Compile-time default paths. Override at runtime via environment variables.

pub const SYSTEMD_LIB_UNIT_DIR: &str = "/usr/lib/systemd/system";
pub const SYSTEMD_FIRST_BOOT_FILE: &str = "/run/systemd/first-boot";
pub const SYSTEMD_MACHINE_ID_FILE: &str = "/etc/machine-id";

pub const IPC_SOCKET_PATH: &str = "/run/system-alphabet/allocator.sock";
pub const SYSTEMA_FDPASS_SOCK: &str = "/run/system-alphabet/fdpass.sock";

pub const SYSTEMA_SHELL_PATH: &str = "/bin/sh";
pub const SYSTEMA_SOCKET_HANDLER_PATH: &str = "/usr/lib/system-alphabet/socket-handler";

pub const UNIT_SEARCH_PATHS: &[&str] = &[
    "/etc/system-alphabet",
    "/run/system-alphabet",
    "/usr/local/lib/system-alphabet",
    "/usr/lib/system-alphabet",
    "/etc/systemd/system",
    "/usr/lib/systemd/system",
    "/lib/systemd/system",
];

pub const GENERATOR_SEARCH_PATHS: &[&str] = &[
    "/run/systemd/generator",
    "/run/systemd/generator.late",
    "/etc/systemd/system-generators",
    "/usr/local/lib/systemd/system-generators",
    "/usr/lib/systemd/system-generators",
    "/lib/systemd/system-generators",
];
"#;

    std::fs::write(&dest_path, content).unwrap();
}
