[package]
name = "systema-sysf"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
libsysa = { path = "../libsysa" }
tokio.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
serde.workspace = true
configparser.workspace = true
async-trait.workspace = true

[build-dependencies]
